apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis-cluster-0
  namespace: public-service
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: "redis-cluster-storage-class"
  nfs:
    # real share directory
    path: /nfs/redis-cluster/redis-cluster00
    # nfs real ip
    server: k8s-node01

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis-cluster-1
  namespace: public-service
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: "redis-cluster-storage-class"
  nfs:
    # real share directory
    path: /nfs/redis-cluster/redis-cluster01
    # nfs real ip
    server: k8s-node01

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis-cluster-2
  namespace: public-service
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: "redis-cluster-storage-class"
  nfs:
    # real share directory
    path: /nfs/redis-cluster/redis-cluster02
    # nfs real ip
    server: k8s-node01

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis-cluster-3
  namespace: public-service
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: "redis-cluster-storage-class"
  nfs:
    # real share directory
    path: /nfs/redis-cluster/redis-cluster03
    # nfs real ip
    server: k8s-node01

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis-cluster-4
  namespace: public-service
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: "redis-cluster-storage-class"
  nfs:
    # real share directory
    path: /nfs/redis-cluster/redis-cluster04
    # nfs real ip
    server: k8s-node01

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis-cluster-5
  namespace: public-service
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: "redis-cluster-storage-class"
  nfs:
    # real share directory
    path: /nfs/redis-cluster/redis-cluster05
    # nfs real ip
    server: k8s-node01
