apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana
  namespace: logging
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: kibana.net
    http:
      paths:
      - backend:
          serviceName: kibana-logging
          servicePort: 5601
